namespace TheLibraryApi.DTOs
{
    public class CreateBookDto
    {
        // here we hide the Id because it will be auto generated by the database
        // when we create a new book record. so we don't need to provide

        // the avilable copies need not to know
        public string Title { get; set; } = string.Empty;
        public string ISBN { get; set; } = string.Empty;

        public int PublishedYear { get; set; }

        public int TotalCopies { get; set; } 

        public int AuthorId { get; set; }


    }


    public class UpdaateBookDto

    {

        public string Title { get; set; } = string.Empty;

        public int publishedYear { get; set; }

        public int totalCopies { get; set; }

        public int AvilableCopies { get; set; }

    }


    // see creat or update at the end response is bookresponse for client so it is stagnant , 


    // What client RECEIVES (response)
    public class BookResponseDto
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string ISBN { get; set; } = string.Empty;
        public int PublishedYear { get; set; }
        public int AvailableCopies { get; set; }
        public int TotalCopies { get; set; }

        // extra response dto from acessing through author and display it
        public string AuthorName { get; set; } = string.Empty; // Flattened from Author
    }



}
